// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SearchPageTestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void searchPageTest() {
    driver.get("https://www.walmart.ca/en");
    driver.manage().window().setSize(new Dimension(1102, 720));
    driver.findElement(By.id("search-form-input")).click();
    driver.findElement(By.id("search-form-input")).sendKeys("macbook");
    driver.findElement(By.id("search-form-input")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector("div:nth-child(1) > .css-1fnwt3w .css-gxbcya")).click();
    driver.findElement(By.id("search-form-input")).click();
    driver.findElement(By.cssSelector(".css-1lxthnz")).click();
    driver.findElement(By.id("search-form-input")).click();
    driver.findElement(By.id("search-form-input")).sendKeys(" ");
    driver.findElement(By.cssSelector(".css-1lxthnz")).click();
    driver.findElement(By.id("search-form-input")).click();
    driver.findElement(By.id("search-form-input")).sendKeys(" sdhkfjssl;fljrs");
    driver.findElement(By.id("search-form-input")).sendKeys(Keys.ENTER);
    driver.findElement(By.id("search-form-input")).click();
    driver.findElement(By.id("search-form-input")).click();
    driver.findElement(By.id("search-form-input")).click();
    driver.findElement(By.id("search-form-input")).click();
    {
      WebElement element = driver.findElement(By.id("search-form-input"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("search-form-input")).click();
    driver.findElement(By.id("search-form-input")).click();
    {
      WebElement element = driver.findElement(By.id("search-form-input"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("search-form-input")).click();
    driver.findElement(By.id("search-form-input")).sendKeys("asdagjaksjgkadsglskjfg");
    driver.findElement(By.id("search-form-input")).sendKeys(Keys.ENTER);
    driver.close();
  }
}
