// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class StoreFinderTestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void storeFinderTest() {
    driver.get("https://www.walmart.ca/en");
    driver.manage().window().setSize(new Dimension(1102, 720));
    driver.findElement(By.cssSelector(".en07u8q1")).click();
    driver.findElement(By.cssSelector(".sfa-search__input")).click();
    driver.findElement(By.cssSelector(".sfa-search__input")).click();
    driver.findElement(By.cssSelector(".sfa-search__input")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".sfa-search__input"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector(".sfa-search__input")).sendKeys("T3H5S1");
    driver.findElement(By.cssSelector(".sfa-wm-btn")).click();
    driver.findElement(By.cssSelector(".sfa-search__input")).click();
    driver.findElement(By.cssSelector(".sfa-search__input")).click();
    driver.findElement(By.cssSelector(".sfa-search__input")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".sfa-search__input"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector(".sfa-search__input")).sendKeys("invalid");
    driver.findElement(By.cssSelector(".sfa-wm-btn")).click();
    driver.findElement(By.cssSelector(".sfa-search__input")).click();
    driver.close();
  }
}
